[APP]
DATASOURCE = 'Apple Watch via Health Fit'
AUTHOR = 'by [DataBooth.com.au](https://www.databooth.com.au)'
NAME = 'Emmaus Walking Mapping App'
CACHED_DATAFILE = 'emmaus_walking.cache.feather'
LAYOUT = 'wide'

[S3] # Cloud Object Storage: https://console.scaleway.com
ACCESS_KEY_ID = 'SCW5MSNHMS37P6Q0ZZV2'   # emmaus_walking credentials
SECRET_ACCESS_KEY = 'app_secrets.toml'
STORAGE_BUCKET_NAME = 'emmaus-walking'
DEFAULT_ACL = 'public-read'
REGION_NAME = 'fr-par'
ENDPOINT_URL = 'https://s3.fr-par.scw.cloud'